require_relative '../node_modules/react-native-macos/scripts/react_native_pods'
require_relative '../../../scripts/clangd-add-xcode-step.rb'

prepare_react_native_project!

ENV['RCT_NEW_ARCH_ENABLED']='1'

ENV['GH_EXAMPLE_APP_NAME'] = 'MacOSExample'

target 'MacOSExample-macOS' do
  platform :macos, '15.0'
  use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => '../node_modules/react-native-macos',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/..",
    :new_arch_enabled => true,
    :fabric_enabled => true
  )

  post_install do |installer|
    react_native_post_install(installer)
  end

  add_clangd_generation_step()
end
