
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateComponentDescriptorH.js
 */

#pragma once

#include <react/renderer/components/rngesturehandler_codegen/RNGestureHandlerDetectorShadowNode.h>
#include <react/renderer/core/ConcreteComponentDescriptor.h>

namespace facebook::react {

class RNGestureHandlerDetectorComponentDescriptor final : public ConcreteComponentDescriptor<RNGestureHandlerDetectorShadowNode> {
  using ConcreteComponentDescriptor::ConcreteComponentDescriptor;
  void adopt(ShadowNode &shadowNode) const override {
    react_native_assert(dynamic_cast<RNGestureHandlerDetectorShadowNode *>(&shadowNode));
    auto detectorShadowNode = dynamic_cast<RNGestureHandlerDetectorShadowNode *>(&shadowNode);
    
    detectorShadowNode->setSize({.width = 300, .height = 300});
    
    ConcreteComponentDescriptor::adopt(shadowNode);
  }
};

} // namespace facebook::react
