name: Bug report
description: Report an issue with Gesture Handler here.
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!

        Before you proceed:

        - Make sure to check whether there are similar issues in the repository
        - Make sure to clean cache in your project. Depending on your setup this could be done by:
          - `yarn start --reset-cache` or
          - `npm run start -- --reset-cache` or
          - `expo start --clear`

  - type: markdown
    attributes:
      value: |
        ## Required information
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please provide a clear, concise and descriptive explanation of what the bug is. Include screenshots or a video if needed. Tell us what were you expecting to happen instead of what is happening now.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to reproduce
      description: Provide a detailed list of steps that reproduce the issue.
      placeholder: |
        1.
        2.
        3.
    validations:
      required: true

  - type: input
    id: repro
    attributes:
      label: A link to a [Gist](https://gist.github.com/), an [Expo Snack](https://snack.expo.io/) or a link to a repository based on [this template](https://github.com/react-native-community/reproducer-react-native) that reproduces the bug.
      description: |
        Please provide code snippet, a Snack or a link to a repository on GitHub under your username that reproduces the issue.
        Here are some tips for providing a minimal example: https://stackoverflow.com/help/mcve.
        Issues without a reproduction are likely to stale.
      placeholder: Link to a Snack or a GitHub repository
    validations:
      required: true

  - type: input
    id: gesture-handler-version
    attributes:
      label: Gesture Handler version
      description: What version of react-native-gesture-handler are you using?
      placeholder: 2.25.0
    validations:
      required: true

  - type: input
    id: react-native-version
    attributes:
      label: React Native version
      description: What version of react-native are you using?
      placeholder: 0.79.0
    validations:
      required: true

  - type: dropdown
    id: platforms
    attributes:
      label: Platforms
      description: On what platform your application is running on?
      multiple: true
      options:
        - Android
        - iOS
        - Web
        - MacOS
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ## Additonal information

        Providing as much information as possible greatly helps us with reproducting the issues.

  - type: dropdown
    id: runtime
    attributes:
      label: JavaScript runtime
      description: What runtime is your application using?
      options:
        - Hermes
        - JSC
        - V8

  - type: dropdown
    id: workflow
    attributes:
      label: Workflow
      description: How your application is managed? Not sure? Read [this part](https://docs.expo.dev/develop/development-builds/introduction/) of Expo documentation.
      options:
        - React Native (without Expo)
        - Using Expo Go
        - Using Expo Prebuild or an Expo development build

  - type: dropdown
    id: architecture
    attributes:
      label: Architecture
      description: What React Native architecture your application is running on? Currently, the New Architecture is enabled by default for every new React Native project.
      options:
        - New Architecture (Fabric)
        - Old Architecture (Paper)

  - type: dropdown
    id: build-type
    attributes:
      label: Build type
      description: What mode your application is running?
      options:
        - Debug mode
        - Release mode

  - type: dropdown
    id: emulator
    attributes:
      label: Device
      description: How are you running your application?
      options:
        - iOS simulator
        - Android emulator
        - Real device

  - type: input
    id: device-model
    attributes:
      label: Device model
      description: What device you are experiencing this problem on? Specify full device name along with the version of the operating system it's running.
      placeholder: ex. Samsung Galaxy A22 (Android 12)

  - type: dropdown
    id: acknowledgements
    attributes:
      label: Acknowledgements
      description: I searched for similar issues in the repository.
      options:
        - 'Yes'
    validations:
      required: true
