blank_issues_enabled: false
contact_links:
  - name: Question
    url: https://github.com/software-mansion/react-native-gesture-handler/discussions/categories/q-a
    about: Please ask and answer questions here.
