# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: ["../../../node_modules"]},
  )', __dir__]).strip

# Use RNRepo in CI builds
if %w[1 true].include?(ENV['CI'].to_s.downcase)
  require Pod::Executable.execute_command('node', ['-p',
    'require.resolve(
      "@rnrepo/build-tools/cocoapods-plugin/lib/plugin.rb",
      {paths: [process.argv[1]]},
    )', __dir__]).strip
end

require_relative '../../../scripts/clangd-add-xcode-step.rb'

ENV['GH_EXAMPLE_APP_NAME'] = 'BasicExample'

platform :ios, min_ios_version_supported
prepare_react_native_project!

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'BasicExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    if %w[1 true].include?(ENV['CI'].to_s.downcase)
      rnrepo_post_install(installer)
    end
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
  end

  add_clangd_generation_step()
end
