require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

# expo autolinking init
require File.join(File.dirname(`node --print "require.resolve('expo/package.json')"`), "scripts/autolinking")
require File.join(File.dirname(`node --print "require.resolve('react-native-macos/package.json')"`), "scripts/react_native_pods")

pod 'React-jsinspector', :path => '../node_modules/react-native-macos/ReactCommon/jsinspector-modern', :modular_headers => true

# set expo env vars
ENV['RCT_NEW_ARCH_ENABLED'] = '0' # '0' for paper, '1' for fabric
ENV['EX_DEV_CLIENT_NETWORK_INSPECTOR'] = "true"

# expo sources linking
use_autolinking_method_symbol = ('use' + '_native' + '_modules!').to_sym
origin_autolinking_method = self.method(use_autolinking_method_symbol)

prepare_react_native_project!

target 'MacOSExample-macOS' do
  platform :macos, '10.15'

  use_expo_modules!
  config = use_native_modules!

  react_native_path = "../node_modules/react-native-macos"

  # Override default react-native path for MacOS building
  config[:reactNativePath] = react_native_path

  use_react_native!(
    :path => react_native_path,
    :hermes_enabled => true,
    :fabric_enabled => ENV['RCT_NEW_ARCH_ENABLED'] == '1',
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  pod 'Swifter', '~> 1.5.0'

  post_install do |installer|
    react_native_post_install(
      installer, 
      react_native_path, 
      :mac_catalyst_enabled => false, 
    )

    # This is necessary for Xcode 14, because it signs resource bundles by default
    # when building for devices.
    installer.target_installation_results.pod_target_installation_results
      .each do |pod_name, target_installation_result|
      target_installation_result.resource_bundle_targets.each do |resource_bundle_target|
        resource_bundle_target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
  
  post_integrate do |installer|
    begin
      expo_patch_react_imports!(installer)
    rescue => e
      Pod::UI.warn e
    end
  end
end
