export {
  findNodeHandle,
  Platform,
  NativeModules,
  DeviceEventEmitter,
  EmitterSubscription,
  UIManager,
  Animated,
  Easing,
  processColor,
  StyleSheet,
  StyleProp,
  ViewStyle,
  View,
  TouchableHighlightProps,
  TouchableOpacityProps,
  ColorValue,
  ViewProps,
  TouchableWithoutFeedbackProps,
  Insets,
  TouchableNativeFeedback,
  ScrollView,
  ScrollViewProps,
  Switch,
  SwitchProps,
  TextInput,
  TextInputProps,
  DrawerLayoutAndroid,
  DrawerLayoutAndroidProps,
  FlatList,
  FlatListProps,
  RefreshControl,
  I18nManager,
  LayoutChangeEvent,
  Keyboard,
  StatusBar,
  StatusBarAnimation,
  NativeSyntheticEvent,
  PixelRatio,
} from 'react-native';

export const isDEV = __DEV__;
