const ReactNative = {
  Animated: { createAnimatedComponent: (a: any) => a },
  Easing: null,
  processColor: null,
  StyleSheet: { create: (a: any) => a },
  StyleProp: null,
  ViewStyle: null,
  View: null,
  TouchableHighlightProps: null,
  TouchableOpacityProps: null,
  ColorValue: null,
  ViewProps: null,
  TouchableWithoutFeedbackProps: null,
  Insets: null,
  TouchableNativeFeedback: null,
  ScrollView: null,
  ScrollViewProps: null,
  Switch: null,
  SwitchProps: null,
  TextInput: null,
  TextInputProps: null,
  DrawerLayoutAndroid: null,
  DrawerLayoutAndroidProps: null,
  FlatList: null,
  FlatListProps: null,
  RefreshControl: null,
  I18nManager: { isRTL: false },
  LayoutChangeEvent: null,
  Keyboard: null,
  StatusBar: null,
  StatusBarAnimation: null,
  NativeSyntheticEvent: null,
  PixelRatio: { get: () => window.devicePixelRatio },
};

export const {
  Animated,
  Easing,
  processColor,
  StyleSheet,
  StyleProp,
  ViewStyle,
  View,
  TouchableHighlightProps,
  TouchableOpacityProps,
  ColorValue,
  ViewProps,
  TouchableWithoutFeedbackProps,
  Insets,
  TouchableNativeFeedback,
  ScrollView,
  ScrollViewProps,
  Switch,
  SwitchProps,
  TextInput,
  TextInputProps,
  DrawerLayoutAndroid,
  DrawerLayoutAndroidProps,
  FlatList,
  FlatListProps,
  RefreshControl,
  I18nManager,
  LayoutChangeEvent,
  Keyboard,
  StatusBar,
  StatusBarAnimation,
  NativeSyntheticEvent,
} = ReactNative;
