
/**
 * This code was generated by
 * [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generated by codegen project: GenerateComponentDescriptorH.js
 */

#pragma once

#include <react/renderer/componentregistry/ComponentDescriptorProviderRegistry.h>
#include <react/renderer/components/rngesturehandler_codegen/ShadowNodes.h>
#include <react/renderer/core/ConcreteComponentDescriptor.h>

#include <react/renderer/components/rngesturehandler_codegen/RNGestureHandlerDetectorComponentDescriptor.h>

namespace facebook::react {

using RNGestureHandlerButtonComponentDescriptor =
    ConcreteComponentDescriptor<RNGestureHandlerButtonShadowNode>;
using RNGestureHandlerRootViewComponentDescriptor =
    ConcreteComponentDescriptor<RNGestureHandlerRootViewShadowNode>;

void FBReactNativeSpec_registerComponentDescriptorsFromCodegen(
    std::shared_ptr<const ComponentDescriptorProviderRegistry> registry);

} // namespace facebook::react
