
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include <react/renderer/components/rngesturehandler_codegen/EventEmitters.h>
#include <react/renderer/components/rngesturehandler_codegen/Props.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <jsi/jsi.h>

#include "RNGestureHandlerDetectorState.h"

namespace facebook::react {

JSI_EXPORT extern const char RNGestureHandlerDetectorComponentName[];

/*
 * `ShadowNode` for <RNGestureHandlerDetector> component.
 */
class RNGestureHandlerDetectorShadowNode final : public ConcreteViewShadowNode<
    RNGestureHandlerDetectorComponentName,
    RNGestureHandlerDetectorProps,
    RNGestureHandlerDetectorEventEmitter,
    RNGestureHandlerDetectorState> {
  public:
    using ConcreteViewShadowNode::ConcreteViewShadowNode;
};

} // namespace facebook::react
