
/**
 * This code was generated by
 * [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be
 * lost once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once

#include <jsi/jsi.h>
#include <react/renderer/components/rngesturehandler_codegen/EventEmitters.h>
#include <react/renderer/components/rngesturehandler_codegen/Props.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <react/renderer/core/LayoutContext.h>

#include "RNGestureHandlerButtonWrapperState.h"

namespace facebook::react {

JSI_EXPORT extern const char RNGestureHandlerButtonWrapperComponentName[];

/*
 * `ShadowNode` for <RNGestureHandlerButtonWrapper> component.
 */
class RNGestureHandlerButtonWrapperShadowNode final
    : public ConcreteViewShadowNode<
          RNGestureHandlerButtonWrapperComponentName,
          RNGestureHandlerButtonWrapperProps,
          RNGestureHandlerButtonWrapperEventEmitter,
          RNGestureHandlerButtonWrapperState> {
 public:
  RNGestureHandlerButtonWrapperShadowNode(
      const ShadowNodeFragment &fragment,
      const ShadowNodeFamily::Shared &family,
      ShadowNodeTraits traits)
      : ConcreteViewShadowNode(fragment, family, traits) {
    initialize();
  }

  RNGestureHandlerButtonWrapperShadowNode(
      const ShadowNode &sourceShadowNode,
      const ShadowNodeFragment &fragment)
      : ConcreteViewShadowNode(sourceShadowNode, fragment) {
    initialize();
  }

  void layout(LayoutContext layoutContext) override;
  void appendChild(const ShadowNode::Shared &child) override;

 private:
  void initialize();
  void prepareChildren();
};

} // namespace facebook::react
