name: Test Paper Architecture integrity
on: [pull_request]
jobs:
  check:
    if: github.repository == 'software-mansion/react-native-gesture-handler'
    runs-on: ubuntu-latest
    concurrency:
      group: static-root-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Use Node.js 18
        uses: actions/setup-node@v2
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install node dependencies
        run: yarn
      - name: Check check integrity
        run: yarn checkIntegrity
