name: Test macOS build
on:
  pull_request:
    paths:
      - '.github/workflows/macos-build.yml'
      - 'RNGestureHandler.podspec'
      - 'apple/**'
      - 'MacOSExample/macos/**'
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    if: github.repository == 'software-mansion/react-native-gesture-handler'
    runs-on: macos-15
    strategy:
      matrix:
        working-directory: [MacOSExample]
    concurrency:
      group: macos-${{ matrix.working-directory }}-${{ github.ref }}
      cancel-in-progress: true
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: Use Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'yarn'
      - name: Install node dependencies
        working-directory: ${{ matrix.working-directory }}
        run: yarn
      - name: Install pods
        working-directory: ${{ matrix.working-directory }}/macos
        run: pod install
      - name: Build app
        working-directory: ${{ matrix.working-directory }}
        run: yarn macos
